---
title: "g-methods: Quick Start in R"
author:
  - name: Herdiantri Sufriyana
    affiliation:
    - &gibi Graduate Institute of Biomedical Informatics, College of Medical
      Science and Technology, Taipei Medical University, Taipei, Taiwan
    - Department of Medical Physiology, College of Medicine, University of
      Nahdlatul Ulama Surabaya, Surabaya, Indonesia
    email: herdiantrisufriyana@unusa.ac.id
  - name: Yu-Wei Wu
    affiliation:
    - *gibi
    - &tmuh Clinical Big Data Research Center, Taipei Medical University
      Hospital, Taipei, Taiwan
  - name: Emily Chia-Yu Su
    affiliation:
    - *gibi
    - *tmuh
    - Research Center for Artificial Intelligence in Medicine, Taipei Medical
      University, Taipei, Taiwan
package: gmethods
abstract: >
  This vignette explains how to conduct causal inference by implementing
  g-methods: g-formula, inverse probability weighting (IPW), and g-estimation.
  These methods are  comprehensively described in Causal Inference: What If book
  by Hernán and Robins using 1 of 4 NHEFS datasets described in this book
  (https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/). This
  vignette only uses nhefs table, a cleaned version of NHEFS data. The
  remaining datasets from that book could be retrieve from cidata R package
  (https://github.com/malcolmbarrett/cidata) for more information.
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Quick Start}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

# Load this package

```{r Load this package, include=F}
library(gmethods)
library(tidyverse)
```


# Load example data for formula and data

```{r Load example data for formula and data}
input=input_example()
formula=input$formula
data=input$data
```


# Conduct g-methods

```{r Conduct g-methods}
results_gformula=gformula(formula,data,verbose=T)
results_ipw=ipw(formula,data,verbose=T)
results_gestimation=gestimation(formula,data,verbose=T)
```

# Results

## g-formula

```{r g-formula}
results_gformula
```


## Inverse probability weighting (IPW)

```{r Inverse probability weighting (IPW)}
results_ipw
```


# g-estimation

```{r g-estimation}
results_gestimation
```
